spring:
  application:
    name: kernel
  flyway:
    baseline-version: 1
    user: sa
    password:
    baseline-description: <<FlyWay BaseLine>>
    enabled: true
    baseline-on-migrate: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:magazine-kernel
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/magazine-realm
          jws-algorithms: RS256
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
server:
  port: 8080
  servlet:
    context-path: "/kernel"

