spring:
  application:
    name: client
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:18080/realms/magazine-realm
            user-name-attribute: preferred_username
        registration:
          client-app-authorization-code:
            provider: keycloak
            client-id: client-web-app
            authorization-grant-type: authorization_code
            client-secret: 2AcI9Tu4kL9anzUDvLQbx1Iy5QXbi1Bz
            scope:
              - microprofile-jwt
              - openid
              - profile

server:
  port: 8081
  servlet:
    context-path: /client
